# Generated by Django 4.0 on 2022-01-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField( max_length=10)),
                ('amount', models.IntegerField()),
                ('tel', models.CharField( max_length=20)),
                ('voucher_id', models.CharField(choices=[('PE', '自取'), ('SE', '郵寄')], default='PP', max_length=2)),
                ('address', models.CharField(max_length=25)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'ordering': ['-ssn'],
            },
        ),
    ]
