# Generated by Django 4.0 on 2022-01-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='amount',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='ssn',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
