# Generated by Django 4.0.1 on 2022-01-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_alter_person_address_alter_person_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-acc']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='ssn',
            new_name='acc',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='voucher_id',
            new_name='take_id',
        ),
    ]
