# Generated by Django 4.0 on 2022-01-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_alter_person_options_rename_ssn_person_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='take_id',
            field=models.CharField(choices=[('PE', '自取'), ('SE', '郵寄')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
